// Generated by gencpp from file vicon_j/position.msg
// DO NOT EDIT!


#ifndef VICON_J_MESSAGE_POSITION_H
#define VICON_J_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <vicon_j/positionRequest.h>
#include <vicon_j/positionResponse.h>


namespace vicon_j
{

struct position
{

typedef positionRequest Request;
typedef positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct position
} // namespace vicon_j


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vicon_j::position > {
  static const char* value()
  {
    return "6d7ca69a7dcb703d43878c445cd2c92c";
  }

  static const char* value(const ::vicon_j::position&) { return value(); }
};

template<>
struct DataType< ::vicon_j::position > {
  static const char* value()
  {
    return "vicon_j/position";
  }

  static const char* value(const ::vicon_j::position&) { return value(); }
};


// service_traits::MD5Sum< ::vicon_j::positionRequest> should match 
// service_traits::MD5Sum< ::vicon_j::position > 
template<>
struct MD5Sum< ::vicon_j::positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vicon_j::position >::value();
  }
  static const char* value(const ::vicon_j::positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vicon_j::positionRequest> should match 
// service_traits::DataType< ::vicon_j::position > 
template<>
struct DataType< ::vicon_j::positionRequest>
{
  static const char* value()
  {
    return DataType< ::vicon_j::position >::value();
  }
  static const char* value(const ::vicon_j::positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vicon_j::positionResponse> should match 
// service_traits::MD5Sum< ::vicon_j::position > 
template<>
struct MD5Sum< ::vicon_j::positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vicon_j::position >::value();
  }
  static const char* value(const ::vicon_j::positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vicon_j::positionResponse> should match 
// service_traits::DataType< ::vicon_j::position > 
template<>
struct DataType< ::vicon_j::positionResponse>
{
  static const char* value()
  {
    return DataType< ::vicon_j::position >::value();
  }
  static const char* value(const ::vicon_j::positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VICON_J_MESSAGE_POSITION_H
