// Generated by gencpp from file vicon_j/positionRequest.msg
// DO NOT EDIT!


#ifndef VICON_J_MESSAGE_POSITIONREQUEST_H
#define VICON_J_MESSAGE_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vicon_j
{
template <class ContainerAllocator>
struct positionRequest_
{
  typedef positionRequest_<ContainerAllocator> Type;

  positionRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , thetax(0.0)
    , thetay(0.0)
    , thetaz(0.0)  {
    }
  positionRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , thetax(0.0)
    , thetay(0.0)
    , thetaz(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _thetax_type;
  _thetax_type thetax;

   typedef float _thetay_type;
  _thetay_type thetay;

   typedef float _thetaz_type;
  _thetaz_type thetaz;




  typedef boost::shared_ptr< ::vicon_j::positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_j::positionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct positionRequest_

typedef ::vicon_j::positionRequest_<std::allocator<void> > positionRequest;

typedef boost::shared_ptr< ::vicon_j::positionRequest > positionRequestPtr;
typedef boost::shared_ptr< ::vicon_j::positionRequest const> positionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vicon_j::positionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vicon_j::positionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vicon_j

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vicon_j': ['/home/ubuntu/catkin_ws/src/vicon_j/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vicon_j::positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vicon_j::positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_j::positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_j::positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_j::positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_j::positionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vicon_j::positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "343f88ee256329e1ad031142d25c7292";
  }

  static const char* value(const ::vicon_j::positionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x343f88ee256329e1ULL;
  static const uint64_t static_value2 = 0xad031142d25c7292ULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_j::positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vicon_j/positionRequest";
  }

  static const char* value(const ::vicon_j::positionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vicon_j::positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
\n\
float32 thetax\n\
float32 thetay\n\
float32 thetaz\n\
\n\
";
  }

  static const char* value(const ::vicon_j::positionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vicon_j::positionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.thetax);
      stream.next(m.thetay);
      stream.next(m.thetaz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct positionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_j::positionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vicon_j::positionRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "thetax: ";
    Printer<float>::stream(s, indent + "  ", v.thetax);
    s << indent << "thetay: ";
    Printer<float>::stream(s, indent + "  ", v.thetay);
    s << indent << "thetaz: ";
    Printer<float>::stream(s, indent + "  ", v.thetaz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VICON_J_MESSAGE_POSITIONREQUEST_H
