// Generated by gencpp from file vicon_j/positionResponse.msg
// DO NOT EDIT!


#ifndef VICON_J_MESSAGE_POSITIONRESPONSE_H
#define VICON_J_MESSAGE_POSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vicon_j
{
template <class ContainerAllocator>
struct positionResponse_
{
  typedef positionResponse_<ContainerAllocator> Type;

  positionResponse_()
    : inPosition(false)  {
    }
  positionResponse_(const ContainerAllocator& _alloc)
    : inPosition(false)  {
  (void)_alloc;
    }



   typedef uint8_t _inPosition_type;
  _inPosition_type inPosition;




  typedef boost::shared_ptr< ::vicon_j::positionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_j::positionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct positionResponse_

typedef ::vicon_j::positionResponse_<std::allocator<void> > positionResponse;

typedef boost::shared_ptr< ::vicon_j::positionResponse > positionResponsePtr;
typedef boost::shared_ptr< ::vicon_j::positionResponse const> positionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vicon_j::positionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vicon_j::positionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vicon_j

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vicon_j': ['/home/ubuntu/catkin_ws/src/vicon_j/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vicon_j::positionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vicon_j::positionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_j::positionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_j::positionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_j::positionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_j::positionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vicon_j::positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a55420e8f99e4d8412cd931d7f58273e";
  }

  static const char* value(const ::vicon_j::positionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa55420e8f99e4d84ULL;
  static const uint64_t static_value2 = 0x12cd931d7f58273eULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_j::positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vicon_j/positionResponse";
  }

  static const char* value(const ::vicon_j::positionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vicon_j::positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool inPosition\n\
\n\
";
  }

  static const char* value(const ::vicon_j::positionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vicon_j::positionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct positionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_j::positionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vicon_j::positionResponse_<ContainerAllocator>& v)
  {
    s << indent << "inPosition: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.inPosition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VICON_J_MESSAGE_POSITIONRESPONSE_H
