// Generated by gencpp from file vicon_j/vicon.msg
// DO NOT EDIT!


#ifndef VICON_J_MESSAGE_VICON_H
#define VICON_J_MESSAGE_VICON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vicon_j
{
template <class ContainerAllocator>
struct vicon_
{
  typedef vicon_<ContainerAllocator> Type;

  vicon_()
    : header()
    , pos()
    , angle()  {
      pos.assign(0.0);

      angle.assign(0.0);
  }
  vicon_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos()
    , angle()  {
  (void)_alloc;
      pos.assign(0.0);

      angle.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _pos_type;
  _pos_type pos;

   typedef boost::array<float, 3>  _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::vicon_j::vicon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_j::vicon_<ContainerAllocator> const> ConstPtr;

}; // struct vicon_

typedef ::vicon_j::vicon_<std::allocator<void> > vicon;

typedef boost::shared_ptr< ::vicon_j::vicon > viconPtr;
typedef boost::shared_ptr< ::vicon_j::vicon const> viconConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vicon_j::vicon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vicon_j::vicon_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vicon_j

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vicon_j': ['/home/ubuntu/catkin_ws/src/vicon_j/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vicon_j::vicon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vicon_j::vicon_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_j::vicon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_j::vicon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_j::vicon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_j::vicon_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vicon_j::vicon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "327bf50c008827ddd61b99f2837fc70c";
  }

  static const char* value(const ::vicon_j::vicon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x327bf50c008827ddULL;
  static const uint64_t static_value2 = 0xd61b99f2837fc70cULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_j::vicon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vicon_j/vicon";
  }

  static const char* value(const ::vicon_j::vicon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vicon_j::vicon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32[3] pos\n\
float32[3] angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vicon_j::vicon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vicon_j::vicon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vicon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_j::vicon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vicon_j::vicon_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VICON_J_MESSAGE_VICON_H
